[project]
name = "houses-ms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.8",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.40.0",
]
